### PR TITLE
Node overview, adding nodes, datatypes, tensor datatypes

### PR DESCRIPTION
**Pull request by chrisgoringe**
A first cut at what docs might look like, as discussed with haohao on Discord.

### CODE REVIEW

**Comment by robinjhuang** [comment]
The structure of the custom node docs you want to add looks great! Let me know when it's ready for further review. Thanks for writing this 😁

**Comment by chrisgoringe** [comment]
I'll take one more read through then put it for review. I'd prefer to work in relatively small PRs if that works for everyone.

**Comment by robinjhuang** [comment]
@chrisgoringe Added some initial review comments. Everything you wrote looks really good and is really informative! Looks like you also used a lot of the Mintlify built-in components like warnings 😄 

Some pages look incomplete. Since all changes will be deployed immediately to the public documentation site, can we remove those until they are written? 

This PR can be merged after that.

**Comment by chrisgoringe** [comment]
Ah, I wasn't aware that the merged docs would automatically go live.

I'll clean it up into a state that should be ok for that. Do you want there to be an indication that this is a WIP, and that more material is coming?

**Comment by chrisgoringe** [comment]
> @chrisgoringe Added some initial review comments. 

Sorry, probably being blind - where have you added review comments? I saw you tweaked the wording of the introduction.

**Comment by robinjhuang** [comment]
> Ah, I wasn't aware that the merged docs would automatically go live.
> 
> I'll clean it up into a state that should be ok for that. Do you want there to be an indication that this is a WIP, and that more material is coming?

Sounds good! Maybe make the PR title : WIP: <title name>?

Also sorry I forgot to submit the review. Added the comments now, but sounds like it was still WIP anyways.

**Comment by chrisgoringe** [comment]
Merged a couple of things I was working on in another branch. I'll now do a read through and clean up, and let you know when I think it's good to go.

**Comment by chrisgoringe** [comment]
OK, I've cleaned up and added the latest version of datatypes and masks etc.. Should be good for review.

**Pull request merged**
